name = "kilconstruction"
compatibility_date = "2024-11-18"

[vars]
UPLOAD_SECRET = "example"
UPLOAD_HOSTNAME = "kilcon.work"

[[r2_buckets]]
binding = "GALLERY_BUCKET"
bucket_name = "kilcon-gallery"
preview_bucket_name = "kilcon-gallery"
