name = "r2-uploader"
main = "index.js"
compatibility_date = "2023-11-11"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "kilcon-gallery"
preview_bucket_name = "kilcon-gallery"

[vars]
UPLOAD_HOSTNAME = "images.kilcon.work"
